# Docker DB (compose service name = "postgres")
spring.datasource.url=jdbc:postgresql://postgres:5432/orders_db
spring.datasource.username=postgres
spring.datasource.password=1234

# For local Docker: auto create/update tables
spring.jpa.hibernate.ddl-auto=update

# Optional: reduce noise if you want
# spring.jpa.show-sql=false


spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
